spring.application.name=life-organizer

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME_LIFE_ORGANIZER}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Gemini AI
gemini.api.key=${GEMINI_API_KEY}

# Port
server.port=8080